install

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,27 +1,33 @@
 #!/usr/bin/env bash
 # This script installs and configures nginx on an Ubuntu server
 
-# Update package index
-apt-get update -y
-
-# Install nginx
-apt-get install nginx -y
-
-# Start nginx if not already started
-if ! ps aux | grep -q '[n]ginx'; then
-    /usr/sbin/nginx
-fi
-
-# Check if nginx is listening on port 80
-if ! netstat -tuln | grep -q ':80'; then
-    echo "Nginx is not listening on port 80"
+sudo apt-get update -y && \
+sudo apt-get install -y nginx
+if [ $? -eq 0 ]
+then
+    echo -e \
+"http {
+    root /var/www/school;
+    index index.html;
+    server {
+        listen 80;
+        location \ {
+        }
+    }
+}
+events {
+}" > /etc/nginx/nginx.conf
+    mkdir -p /var/www/school
+    echo "Hello World!" > \
+	/var/www/school/index.html
+    service nginx start
+    if [ $? -ne 0 ]
+    then
+	"Problem starting nginx"
+	exit 1
+    fi
+else
+    echo "Could not install nginx"
     exit 1
 fi
-
-# Create a temporary index.html file with "Hello World!"
-echo "Hello World!" > /var/www/html/index.html
-
-# Restart nginx
-kill -HUP $(cat /var/run/nginx.pid)
-
 exit 0
